version: "3"

services:                                                                                                                                                                                  
  web:
    build: .
    ports:
      - "80:8080"
  mysql:                                                                                                                                                                                           
    image: mysql:5.6
    ports:                                                                                                                                                                                         
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
